### ISSUE TITLE
[feature/kkuleogi-8] 도서API, 도서 성향 추출 구현

### ISSUE THREAD

**Issue by taeyeon0319** [Famailyship-org/api.checkkuleogi.org#15]
## 어떤 기능인가요?

>책 등록 시 줄거리를 통해 책의 성향 출력

## 작업 상세 내용

- [x] chatGPT API 연결
- [x] 도서 등록 API - 등록 시 줄거리를 통해 책의 성향 출력

**Comment by YaeJinKwon** [comment]
좋아요!
